### PR TITLE
update commands

### PR DESCRIPTION
**Pull request by sabas1080**
Update command configure

### CODE REVIEW

**Comment by rpcme** [comment]
The create-certificate command doesn't exist any longer?

aws iot create-keys-and-certificate --set-as-active --certificate-pem-outfile cert.pem --public-key-outfile publicKey.pem --private-key-outfile privateKey.pem

And ... it doesn't seem like the use of endpoint URLs are valid any longer either?

I think this PR needs to be rejected and the doc refactored to reflect the CLI's current state.

**Comment by w4ilun** [comment]
@rpcme agreed, the commands and docs need to be fixed since the AWS IoT CLI has been updated. Accepting any PR with updates or until we find resources to resolve these issues.

**Comment by rpcme** [comment]
I put in a separate PR to get this issue solved.

**Comment by rpcme** [comment]
I think this issue can be closed.

**Comment by w4ilun** [comment]
Thanks @rpcme

**Pull request closed without merging**
